# ===============
# Header
# ===============
menu:
  Home: /
  Archives: /archives
  About: /about
banner: "images/banner.jpg"

# ===============
# Sidebar
# ===============
widgets:
  - category
  - tagcloud

# ===============
# Miscellaneous
# ===============
google_analytics: UA-80426918-1
cloudflare_analytics: 0256d46589084276b1a235490b30549c
twitter: hnliuzesen
