# ===============
# Header
# ===============
menu:
  Home: /
  Archives: /archives
  About: /about
banner: "images/banner.jpg"

# ===============
# Sidebar
# ===============
widgets:
  - category
  - tagcloud

# ===============
# Miscellaneous
# ===============
twitter: hnliuzesen
