name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - source

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: source
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v5.0.4
      - name: Code Scan
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
